const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'..');
const pure={};vm.runInNewContext(fs.readFileSync(path.join(root,'web/swing.js'),'utf8'),pure);
const sw=pure.Swing;
let checks=0;function check(value,message){assert(value,message);checks++;}
const calendar={years:{2026:{sessions:['2026-09-24','2026-09-25','2026-09-29','2026-09-30','2026-10-01','2026-10-02','2026-12-31']},2027:{sessions:['2027-01-04']}}};
const meta={date:'20260930',tradingCalendar:calendar};
const now=Date.parse('2026-09-30T23:00:00+08:00');
const stock={code:'2330',date:'20260930',price:100,likely:true,selectionQualified:true,snapshotStage:'full',techReady:true,financialReady:true,institutionalReady:true,newsReady:true,ohlcv:{available:true},suggestedStopPrice:94,suggestedTargetPrice:115,signalHorizonDays:20,officialTrading:{fetchHealthy:true,evaluationDate:'2026-09-30',tradabilityVerified:true}};
const pos={cost:100,shares:100,date:'2026-09-25',stop:94,target:115,horizon:20};
check(sw.heldSessions(calendar,'20260925','20260930')===2,'weekend and holiday excluded');
check(sw.heldSessions(calendar,'20261231','20270104')===1,'cross year');
check(sw.heldSessions(calendar,'20261231','20280104')===null,'missing year not guessed');
check(sw.heldSessions(calendar,'20260928','20260930')===null,'holiday entry invalid');
check(sw.iso('20260230')===null,'invalid dates rejected');
check(sw.freshness(stock,meta,Date.parse('2026-10-01T09:00:00+08:00'))===null,'prior close allowed before scheduled update');
check(!!sw.freshness(stock,meta,Date.parse('2026-10-01T19:00:00+08:00')),'stale after close update');
check(sw.entry(stock,meta,now).label==='規則候選・策略待驗證','complete data does not imply validated buy');
check(sw.entry({...stock,suggestedStopPrice:0},meta,now).stop===null,'missing stop not fabricated');
check(sw.entry({...stock,suggestedTargetPrice:0},meta,now).target===null,'missing target not fabricated');
check(sw.entry({...stock,postCloseAction:'只觀察不追'},meta,now).label.startsWith('暫不進場'),'upstream watch cannot become buy');
check(sw.entry({...stock,officialTrading:null},meta,now).missing.some(x=>x.includes('交易')),'missing status blocks');
check(sw.validatePosition(pos,null,calendar,'2026-09-30')===null,'valid position');
check(!!sw.validatePosition({...pos,stop:93},pos,calendar,'2026-09-30'),'cannot lower stop');
check(!!sw.validatePosition({...pos,date:'2026-09-29'},pos,calendar,'2026-09-30'),'cannot reset entry day');
check(!!sw.validatePosition({...pos,shares:1.5},null,calendar,'2026-09-30'),'integer shares required');
check(!!sw.validatePosition({...pos,date:'2026-10-01'},null,calendar,'2026-09-30'),'future entry rejected');
check(sw.exit(stock,pos,meta,now).rank===5,'valid no trigger');
check(sw.exit({...stock,date:'20260929'},pos,meta,now).rank===1,'mismatched quote is unknown');
check(sw.exit({...stock,price:null},pos,meta,now).rank===1,'missing quote not hold');
const stopped=sw.exit({...stock,price:90},pos,meta,now);
check(stopped.rank===0 && stopped.trigger.price===90,'stop priority');
check(sw.exit({...stock,price:110},{...pos,trigger:stopped.trigger},meta,now).rank===0,'sticky stop survives rebound');
check(sw.exit({...stock,price:90},pos,meta,Date.parse('2026-10-02T20:00:00+08:00')).rank===0,'old observed breach retained');
check(sw.exit({...stock,price:90,ohlcv:{events:[{date:'2026-09-29',type:'splits'}]}},pos,meta,now).label.includes('公司行動'),'split is not assumed stop loss');
check(sw.exit({...stock,price:116},pos,meta,now).rank===2,'target reached');
check(sw.exit(stock,{...pos,horizon:2},meta,now).rank===2,'time review reached');
check(sw.researchText('營收增加；回測 cohort 勝率 76%；量能擴大')==='營收增加；量能擴大','old cohort claims removed');
check(!sw.backtestHtml({generatedAt:'<script>',pointInTimeConsistentSummary:{10:{sampleCount:2,winRatePct:100}}}).includes('<script>'),'backtest escaped');

// Exercise the actual page functions with DOM/storage boundaries stubbed, no browser package needed.
const nodes=new Map(),storage=new Map();let quota=false;
function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',checked:false,style:{},classList:{add(){},remove(){},toggle(){}},closest(){return this;},querySelector(){return this;},getContext(){return {};},appendChild(){},setAttribute(){}});return nodes.get(id);}
const document={getElementById:node,querySelectorAll:()=>[],querySelector:()=>node('query'),createElement:()=>node('created'),addEventListener(){}};
const ctx=vm.createContext({console,document,location:{protocol:'http:',href:'http://localhost/index.html',pathname:'/index.html',search:''},URLSearchParams,URL,Intl,Date,Math,Number,Set,Map,JSON,window:{addEventListener(){},confirm:()=>true,alert(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem(k,v){if(quota)throw Error('quota');storage.set(k,v);},removeItem:k=>storage.delete(k)},Chart:function(){this.destroy=()=>{};},setTimeout:()=>0,clearTimeout(){}});
ctx.window.location=ctx.location;
for(const name of ['technical-overlays.js','swing.js','swing-ui.js']) vm.runInContext(fs.readFileSync(path.join(root,'web',name),'utf8'),ctx);
const html=fs.readFileSync(path.join(root,'web/index.html'),'utf8');
const main=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(s=>s.includes('const SMAXES'));
vm.runInContext(main.replace(/\ninit\(\);\s*$/,'\n'),ctx);
ctx.fixture=JSON.parse(fs.readFileSync(path.join(root,'web/data/latest.json'),'utf8').replace(/^\uFEFF/,''));
ctx.calendar=JSON.parse(fs.readFileSync(path.join(root,'web/data/trading_calendar.json'),'utf8'));
ctx.ohlcv=JSON.parse(fs.readFileSync(path.join(root,'web/data/ohlcv_quality.json'),'utf8'));
ctx.official=JSON.parse(fs.readFileSync(path.join(root,'web/data/trading_status.json'),'utf8'));
vm.runInContext(`S.meta={...fixture,tradingCalendar:calendar};S.all=fixture.rows.map(s=>({...s,shortScore:calcShortScore(s),midScore:calcMidScore(s),ohlcv:ohlcv.stocks[s.code],officialTrading:attachTradingStatus(official,fixture.date,s)}));renderSwingBoard();`,ctx);
check(node('swing-board').innerHTML.includes('尚無實際持股'),'watchlist never imported as holding');
// Rendering every real stock detects missing variables in less common detail branches.
vm.runInContext(`for(const s of S.all) renderDB(s,[]);`,ctx);
check(node('db-body').innerHTML.includes('我的實際持股'),'detail renders with new editor');
check(!node('db-body').innerHTML.includes('首次 50%'),'conflicting fixed allocation removed');
const realCode=ctx.fixture.rows[0].code;
ctx.realCode=realCode;
vm.runInContext(`toggleWL(realCode);renderDB(S.all[0],[]);renderSwingBoard();`,ctx);
check(node('db-body').innerHTML.includes('不是實際交易損益'),'observation labelled explicitly');
check(node('swing-board').innerHTML.includes('尚無實際持股'),'starring does not create holding');
for(const [k,v] of Object.entries({cost:'100',shares:'100',date:'2026-09-24',horizon:'20',stop:'94',target:'115'}))node(`spos-${k}-${realCode}`).value=v;
vm.runInContext(`saveSwingPosition({preventDefault(){}},realCode)`,ctx);
assert(storage.has('_swing_positions_v1'),node(`spos-error-${realCode}`).textContent);
check(JSON.parse(storage.get('_swing_positions_v1')).active[realCode].stop===94,'explicit position persists');
node(`spos-stop-${realCode}`).value='90';vm.runInContext(`saveSwingPosition({preventDefault(){}},realCode)`,ctx);
check(node(`spos-error-${realCode}`).textContent.includes('不能下調'),'UI rejects lower stop');
check(JSON.parse(storage.get('_swing_positions_v1')).active[realCode].stop===94,'failed save preserves original');
node(`spos-stop-${realCode}`).value='96';quota=true;vm.runInContext(`saveSwingPosition({preventDefault(){}},realCode)`,ctx);quota=false;
check(node(`spos-error-${realCode}`).textContent.includes('無法保存'),'storage failures visible');
vm.runInContext(`archiveSwingPosition(realCode)`,ctx);
check(JSON.parse(storage.get('_swing_positions_v1')).closed.length===1,'archive preserves history');
storage.set('_swing_positions_v1','bad json');vm.runInContext('swingPositions=null;renderSwingBoard()',ctx);
check(storage.get('_swing_positions_v1')==='bad json' && node('swing-board').innerHTML.includes('無法讀取'),'corrupt storage preserved');
for(const match of fs.readFileSync(path.join(root,'web/performance/performance_latest.html'),'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
console.log(`Swing UI: ${checks} behavior checks and ${ctx.fixture.rows.length} real-stock detail renders passed`);
